### PR TITLE
Change lbu timeout

### LINKED ISSUE #106: Idempotency of delete functions
### What happened

If the VM is not present in the Iaas, during the deletion, the plugin is stuck trying to delete the VM which is not not there.

### Step to reproduce

Delete my current cluster and apply a new one directly

### Expected to happen

RAS

### Add anything

N/A

### cluster-api output

```
1.6644153747449656e+09	INFO	controller.oscmachine	### VmiD ###	{"reconciler group": "infrastructure.cluster.x-k8s.io", "reconciler kind": "OscMachine", "name": "test-md-0-2c6vn", "namespace": "cluster-api-provider-outscale-system", "machine": "test-md-0-596cb6f4c4-2bcd5", "vmId": ""}
1.6644153748067715e+09	ERROR	controller.oscmachine	Reconciler error	{"reconciler group": "infrastructure.cluster.x-k8s.io", "reconciler kind": "OscMachine", "name": "test-md-0-2c6vn", "namespace": "cluster-api-provider-outscale-system", "error": "400 Bad Request"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227
```

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): v1.24.4
- cluster-api-provider-outscale version: v0.1.0
```

### LINKED ISSUE #173: Deletion of Loadbalancer and vm exceed the timeout
### What happened

The time of loadBalancer deletion execeed the timeout to delete its security group (https://github.com/outscale-dev/cluster-api-provider-outscale/blob/c427fe03771e9c0802c5f3ba5ef95cf42c1cd1ca/controllers/osccluster_securitygroup_controller.go#L206)

The time of vm deletion execeed the timeout (https://github.com/outscale-dev/cluster-api-provider-outscale/blob/c427fe03771e9c0802c5f3ba5ef95cf42c1cd1ca/cloud/services/compute/vm.go#L238)

### Step to reproduce

Launch several times cluster-api to find the error.

### Expected to happen

Deletion succeded

### Add anything

None

### cluster-api output

[manager] 1.6672076385193148e+09 ERROR controller.osccluster Reconciler error {"reconciler group": "infrastructure.cluster.x-k8s.io", "reconciler kind": "OscCluster", "name": "cluster-api", "namespace": "default", "error": "409 Conflict Can not delete securityGroup because to waiting loadbalancer to be delete timeout for Osccluster default/cluster-api Can not delete securityGroup for Osccluster default/cluster-api"} [manager] sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem [manager] /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 [manager] sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2 [manager] /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): v1.22.5-rancher1-1
- OS (e.g. from `/etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1160.15.2.el7.x86_64
- cluster-api-provider-outscale version: v1.1.3
- cluster-api version: current
- Install tools: calico, ingress-nginx, osc-ccm
- Kubernetes Distribution: rke
- Kubernetes Distribution version: v1.3.4
```

### PR DESCRIPTION
**Pull request by outscale-vbr**
**What type of PR is this?**
/kind bug   

**What this PR does / why we need it**:
Delete vm (for vm and loadbalancer) can be too long so it can execeded timeout.
Machine should be able to be destroyed with any state (provisioning, provisioned, running)
Also to have idempotency vm functions

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #173
Fixes #106

**Special notes for your reviewer**:
It incluse also vm unit test refacto.

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [x] adds unit tests

### CODE REVIEW

**Comment by outscale-vbr** [comment]
Closes https://github.com/outscale-dev/cluster-api-provider-outscale/issues/106

File: controllers/osccluster_securitygroup_controller.go [hunk 1]
```diff
@@ -206,7 +206,7 @@ func reconcileSecurityGroupRule(ctx context.Context, clusterScope *scope.Cluster
 func deleteSecurityGroup(ctx context.Context, clusterScope *scope.ClusterScope, securityGroupId string, securityGroupSvc security.OscSecurityGroupInterface, clock_time clock.Clock) (reconcile.Result, error) {
 	clusterScope.Info("Check loadbalancer deletion")
 
-	currentTimeout := clock_time.Now().Add(time.Second * 20)
+	currentTimeout := clock_time.Now().Add(time.Second * 600)
```
Comment (outscale-hmi) [inline controllers/osccluster_securitygroup_controller.go:209]: one question, how did you end up choosing this numbers ? (600 rather than 20 for example? )

**Review by outscale-mdr — CHANGES_REQUESTED** [review]

File: controllers/oscmachine_vm_controller.go [hunk 2]
```diff
@@ -528,15 +528,10 @@ func reconcileDeleteVm(ctx context.Context, clusterScope *scope.ClusterScope, ma
...
-		machineScope.Info("The desired vm does not exist anymore", "vmName", vmName)
-		controllerutil.RemoveFinalizer(oscmachine, "")
-		return reconcile.Result{}, nil
-	}
 	if vmSpec.PublicIpName != "" {
 		linkPublicIpRef := machineScope.GetLinkPublicIpRef()
 		publicIpName := vmSpec.PublicIpName + "-" + clusterScope.GetUID()
-		err = vmSvc.CheckVmState(5, 120, "running", vmId)
+		err = vmSvc.CheckVmState(5, 240, "running", vmId)
 		if err != nil {
```
[the remark this answers is not in the document]
Comment (outscale-vbr) [reply controllers/oscmachine_vm_controller.go:535]: Thanks.
You right.
In vpc, unlink does not depends on vm state.
And unlinkLoadBalancerBackendMachin does not depend on vm state.
I will remove it from reconcileDelete.

File: controllers/osccluster_securitygroup_controller.go (hunk 1 above)
Comment (outscale-mdr) [reply controllers/osccluster_securitygroup_controller.go:209]: This is just a remark but rather than setting timeouts, is it possible in case of failure to just try in the next reconciliation loop ?

Comment (outscale-vbr) [reply controllers/osccluster_securitygroup_controller.go:209]: We can set reconcile.Result{RequeueAfter: 30 * time.Second}

https://github.com/outscale-dev/cluster-api-provider-outscale/blob/ebe14a6c11a6cd797dc8a66d0911b6e2f2c8edcf/controllers/oscmachinetemplate_capacity_controller.go#L78

Comment (outscale-vbr) [reply controllers/osccluster_securitygroup_controller.go:209]: It will be looked during this refacto https://github.com/outscale-dev/cluster-api-provider-outscale/issues/183

**Comment by outscale-vbr** [comment]
@outscale-mdr @outscale-hmi Are you ok with the latest changes ?

**Review by outscale-hmi — APPROVED** [review]
LGTM
